export const RUNMQ_INSTANCE = Symbol('RUNMQ_INSTANCE');
export const RUNMQ_MODULE_OPTIONS = Symbol('RUNMQ_MODULE_OPTIONS');

export const RUNMQ_PROCESSOR_METADATA = 'RUNMQ_PROCESSOR';
export const RUNMQ_HANDLER_METADATA = 'RUNMQ_HANDLER';
